services:
  
  # Postgres
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: lsgroup
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
    ports:
      - "5432:5432"