services:
  
  # Postgres
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: runners
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_NAME: LS
    ports:
      - "5432:5432"